CREATE TABLE `topics` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`hook` text NOT NULL,
	`angle` text NOT NULL,
	`category` text NOT NULL,
	`status` text DEFAULT 'radar' NOT NULL,
	`platforms` text DEFAULT '全平台' NOT NULL,
	`source_platform` text DEFAULT '自主策划' NOT NULL,
	`source_name` text DEFAULT '私人选题系统' NOT NULL,
	`source_url` text DEFAULT '' NOT NULL,
	`why_now` text DEFAULT '' NOT NULL,
	`evidence` text DEFAULT '' NOT NULL,
	`shooting` text DEFAULT '' NOT NULL,
	`content_format` text DEFAULT '真人口播' NOT NULL,
	`risk` text DEFAULT '' NOT NULL,
	`tags` text DEFAULT '' NOT NULL,
	`score_pain` integer DEFAULT 0 NOT NULL,
	`score_evidence` integer DEFAULT 0 NOT NULL,
	`score_persona` integer DEFAULT 0 NOT NULL,
	`score_repeatability` integer DEFAULT 0 NOT NULL,
	`score_timeliness` integer DEFAULT 0 NOT NULL,
	`score_ease` integer DEFAULT 0 NOT NULL,
	`score_total` integer DEFAULT 0 NOT NULL,
	`is_pinned` integer DEFAULT false NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
